import socket
import getpass
print()
print(" _  _ ___   ___              _ _       ")
print("| || |__ \ / _ \            (_) |      ")
print("| || |_ ) | | | | __ ___   ___| | __ _ ")
print("|__   _/ /| | | |/ _` \ \ / / | |/ _` |")
print("   | |/ /_| |_| | (_| |\ V /| | | (_| |")
print("   |_|____|\___/ \__,_| \_/ |_|_|\__,_|")
print()
print() 
user = getpass.getuser()
hostname = socket.gethostname()
ip = socket.gethostbyname(hostname)

print("+---------------------------------------------------+")
print("| - Tu nombre de Usuario es: " + user )
print("| - Tu direción IP es: " + ip)
print("| - El nombre de tu Ordenador es: " + hostname )
print("+---------------------------------------------------+")
